## Multiple Linear Regression from scratch for sklearn diabetes dataset and compare results with sklearn LinearRegression

#### Import basic libraries

In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

### Gather and explore diabetes dataset from sklearn

In [2]:
X, y = load_diabetes(return_X_y=True)

In [3]:
print(X.shape)
X

(442, 10)


array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
print(y.shape)
y

(442,)


array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

#### Split dataset into train and test

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

X_train.shape, X_test.shape

((353, 10), (89, 10))

### Implement Multiple Linear Regression using sklearn on diabetes dataset

#### Initialize Linear Regression Model

In [6]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

#### Train Linear Regression Model

In [7]:
regressor.fit(X_train, y_train)

LinearRegression()

#### Predict test records

In [8]:
y_pred = regressor.predict(X_test)

#### Evaluate model based on R2 score

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4399338661568968

#### Get sklearn Linear Regression trained model's coefficients and intercept to compare later with the Linear Regression implemented from scratch

In [10]:
regressor.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [11]:
regressor.intercept_

151.88331005254167

### Implement Multiple Linear Regression from scratch and test results on dieabetes dataset

#### Linear Regression generalized model from scratch

In [12]:
class LinearRegressionScratch:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self, X, y):
        X = np.hstack((np.ones((X.shape[0], 1)), X))
        # coeffients = (X.T @ X)^-1 @ X.T @ y
        coeffients = np.linalg.inv(X.T @ X) @ X.T @ y
        print(coeffients.shape)
        # Beta1, Beta2, ..., BetaN
        self.coef_ = coeffients[1:]
        # Beta0
        self.intercept_ = coeffients[0]

    def predict(self, X):
        return X @ self.coef_ + self.intercept_

#### Initialize Linear Regression Model

In [13]:
regressor_scratch = LinearRegressionScratch()

#### Train Linear Regression Model

In [14]:
regressor_scratch.fit(X_train, y_train)

(11,)


#### Predict test records

In [15]:
y_pred_scratch = regressor_scratch.predict(X_test)

#### Evaluate model based on R2 score

In [16]:
r2_score(y_test, y_pred_scratch)

0.4399338661568968

In [17]:
regressor_scratch.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [18]:
regressor_scratch.intercept_

151.88331005254167

### Conclusion

#### R2 Score, coefficients, and intercept from the linear regression model implemented from scratch matches the R2 Score, coefficients, and intercept of the sklearn linear regression model.